// <auto-generated />
using System;
using Bliss.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bliss.Infrastructure.Migrations
{
    [DbContext(typeof(BlissDbContext))]
    [Migration("20260920073126_Phase3EvaluationAudit")]
    partial class Phase3EvaluationAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bliss.Domain.Entities.AdInventorySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("StartSecond")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("SlotType");

                    b.ToTable("AdInventorySlots", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Advertiser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Website")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Advertisers", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("CommissionPercentage")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<string>("CommissionType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ExternalOpportunityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("FixedFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Language")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MarketCountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserProgramId");

                    b.HasIndex("ExternalOpportunityId");

                    b.HasIndex("Status");

                    b.ToTable("AdvertiserOpportunities", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalProgramId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("ExternalProgramId");

                    b.HasIndex("Status");

                    b.ToTable("AdvertiserPrograms", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AffiliateNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<string>("Website")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("AffiliateNetworks", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.BlissMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserOpportunityId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<Guid>("RuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("CREATED");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserOpportunityId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RuleVersionId");

                    b.HasIndex("Status");

                    b.ToTable("BlissMatches", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("DRAFT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CampaignPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdInventorySlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("CREATED");

                    b.HasKey("Id");

                    b.HasIndex("AdInventorySlotId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("Status");

                    b.ToTable("CampaignPlacements", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalContentId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ExternalContentId");

                    b.ToTable("ContentItems", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Creator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AudienceSize")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EngagementLevel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("FemalePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("MalePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrimaryAgeRange")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PrimaryGeography")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrimaryLanguage")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Creators", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CreatorPlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalProfileId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("Followers")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastCollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ExternalProfileId");

                    b.HasIndex("Platform");

                    b.ToTable("CreatorPlatforms", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.DataProvenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfidenceLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UNKNOWN");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt");

                    b.HasIndex("FieldName");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("DataProvenances", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.EligibilityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlissMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BlissMatchId");

                    b.HasIndex("CheckType");

                    b.ToTable("EligibilityChecks", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchEvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("BlissMatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("MatchStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OutputSnapshot")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<Guid>("RuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("CREATED");

                    b.HasKey("Id");

                    b.HasIndex("BlissMatchId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RuleVersionId");

                    b.ToTable("MatchEvaluationRuns", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchScoreComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlissMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal?>("Score")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("BlissMatchId");

                    b.HasIndex("ComponentName");

                    b.ToTable("MatchScoreComponents", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.NetworkAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AffiliateNetworkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UNKNOWN");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("AffiliateNetworkId");

                    b.HasIndex("ExternalAccountId");

                    b.HasIndex("Status");

                    b.ToTable("NetworkAccesses", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.ProgramAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UNKNOWN");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserProgramId");

                    b.HasIndex("Status");

                    b.ToTable("ProgramAccesses", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.RuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DocumentJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Version");

                    b.ToTable("RuleVersions", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdInventorySlot", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.ContentItem", "ContentItem")
                        .WithMany("AdInventorySlots")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserOpportunity", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdvertiserProgram", "AdvertiserProgram")
                        .WithMany("Opportunities")
                        .HasForeignKey("AdvertiserProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvertiserProgram");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserProgram", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany("Programs")
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.BlissMatch", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdvertiserOpportunity", "AdvertiserOpportunity")
                        .WithMany("BlissMatches")
                        .HasForeignKey("AdvertiserOpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany("BlissMatches")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.RuleVersion", "RuleVersion")
                        .WithMany("BlissMatches")
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvertiserOpportunity");

                    b.Navigation("Creator");

                    b.Navigation("RuleVersion");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CampaignPlacement", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdInventorySlot", "AdInventorySlot")
                        .WithMany("CampaignPlacements")
                        .HasForeignKey("AdInventorySlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Placements")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.ContentItem", "ContentItem")
                        .WithMany("CampaignPlacements")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdInventorySlot");

                    b.Navigation("Campaign");

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.ContentItem", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany("ContentItems")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CreatorPlatform", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany("Platforms")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.EligibilityCheck", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.BlissMatch", "BlissMatch")
                        .WithMany("EligibilityChecks")
                        .HasForeignKey("BlissMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlissMatch");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchEvaluationRun", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.BlissMatch", "BlissMatch")
                        .WithMany()
                        .HasForeignKey("BlissMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.RuleVersion", "RuleVersion")
                        .WithMany()
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlissMatch");

                    b.Navigation("Creator");

                    b.Navigation("RuleVersion");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchScoreComponent", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.BlissMatch", "BlissMatch")
                        .WithMany("ScoreComponents")
                        .HasForeignKey("BlissMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlissMatch");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.NetworkAccess", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany("NetworkAccesses")
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.AffiliateNetwork", "AffiliateNetwork")
                        .WithMany("NetworkAccesses")
                        .HasForeignKey("AffiliateNetworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");

                    b.Navigation("AffiliateNetwork");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.ProgramAccess", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdvertiserProgram", "AdvertiserProgram")
                        .WithMany("ProgramAccesses")
                        .HasForeignKey("AdvertiserProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvertiserProgram");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdInventorySlot", b =>
                {
                    b.Navigation("CampaignPlacements");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Advertiser", b =>
                {
                    b.Navigation("NetworkAccesses");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserOpportunity", b =>
                {
                    b.Navigation("BlissMatches");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserProgram", b =>
                {
                    b.Navigation("Opportunities");

                    b.Navigation("ProgramAccesses");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AffiliateNetwork", b =>
                {
                    b.Navigation("NetworkAccesses");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.BlissMatch", b =>
                {
                    b.Navigation("EligibilityChecks");

                    b.Navigation("ScoreComponents");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Placements");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.ContentItem", b =>
                {
                    b.Navigation("AdInventorySlots");

                    b.Navigation("CampaignPlacements");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Creator", b =>
                {
                    b.Navigation("BlissMatches");

                    b.Navigation("ContentItems");

                    b.Navigation("Platforms");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.RuleVersion", b =>
                {
                    b.Navigation("BlissMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
