// <auto-generated />
using System;
using Bliss.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bliss.Infrastructure.Migrations
{
    [DbContext(typeof(BlissDbContext))]
    partial class BlissDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bliss.Domain.Entities.AdInventorySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("StartSecond")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("SlotType");

                    b.ToTable("AdInventorySlots", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Advertiser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Website")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Advertisers", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("CommissionPercentage")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<string>("CommissionType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ExternalOpportunityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("FixedFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Language")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MarketCountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserProgramId");

                    b.HasIndex("ExternalOpportunityId");

                    b.HasIndex("Status");

                    b.ToTable("AdvertiserOpportunities", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalProgramId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("ExternalProgramId");

                    b.HasIndex("Status");

                    b.ToTable("AdvertiserPrograms", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AffiliateNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<string>("Website")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("AffiliateNetworks", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.BlissMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserOpportunityId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<Guid>("RuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("CREATED");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserOpportunityId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RuleVersionId");

                    b.HasIndex("Status");

                    b.ToTable("BlissMatches", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdvertiserOpportunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("DRAFT");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserOpportunityId");

                    b.HasIndex("Status");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CampaignPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdInventorySlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BlissMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("CREATED");

                    b.HasKey("Id");

                    b.HasIndex("AdInventorySlotId");

                    b.HasIndex("BlissMatchId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("Status");

                    b.ToTable("CampaignPlacements", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CampaignPlacementRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdInventorySlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserOpportunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlissMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignPlacementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InputSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatorLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AdInventorySlotId");

                    b.HasIndex("AdvertiserOpportunityId");

                    b.HasIndex("BlissMatchId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CampaignPlacementId");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("CampaignPlacementRuns", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalContentId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ExternalContentId");

                    b.ToTable("ContentItems", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Creator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AudienceSize")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EngagementLevel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("FemalePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("MalePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrimaryAgeRange")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PrimaryGeography")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrimaryLanguage")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Creators", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CreatorIngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorPlatformId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)");

                    b.Property<string>("InputSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("CreatorId");

                    b.HasIndex("CreatorPlatformId");

                    b.HasIndex("IdentityKey");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("CreatorIngestionRuns", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CreatorPlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalProfileId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("Followers")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityKey")
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)");

                    b.Property<DateTime?>("LastCollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ExternalProfileId");

                    b.HasIndex("IdentityKey")
                        .IsUnique()
                        .HasFilter("\"IdentityKey\" IS NOT NULL");

                    b.HasIndex("Platform");

                    b.ToTable("CreatorPlatforms", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.DataProvenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfidenceLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UNKNOWN");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt");

                    b.HasIndex("FieldName");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("DataProvenances", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.EligibilityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlissMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BlissMatchId");

                    b.HasIndex("CheckType");

                    b.ToTable("EligibilityChecks", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchEvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("BlissMatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("MatchStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OutputSnapshot")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<Guid>("RuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("CREATED");

                    b.HasKey("Id");

                    b.HasIndex("BlissMatchId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RuleVersionId");

                    b.ToTable("MatchEvaluationRuns", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchFormationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserOpportunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlissMatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EvaluateOnCreate")
                        .HasColumnType("boolean");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InputSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RuleVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserOpportunityId");

                    b.HasIndex("BlissMatchId");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RuleVersionId");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("MatchFormationRuns", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchReviewDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlissMatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InputSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MatchEvaluationRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ResultingMatchStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReviewerLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BlissMatchId");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("CreatorId");

                    b.HasIndex("MatchEvaluationRunId");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("MatchReviewDecisions", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchScoreComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlissMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal?>("Score")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("BlissMatchId");

                    b.HasIndex("ComponentName");

                    b.ToTable("MatchScoreComponents", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.NetworkAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AffiliateNetworkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UNKNOWN");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("AffiliateNetworkId");

                    b.HasIndex("ExternalAccountId");

                    b.HasIndex("Status");

                    b.ToTable("NetworkAccesses", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.ProgramAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UNKNOWN");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserProgramId");

                    b.HasIndex("Status");

                    b.ToTable("ProgramAccesses", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.RuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DocumentJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Version");

                    b.ToTable("RuleVersions", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerAgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LogicalRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("OutputBrandDnaVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OutputMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromptPackVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TriggerMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("OutputBrandDnaVersionId");

                    b.HasIndex("OutputMessageId");

                    b.HasIndex("SessionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TriggerMessageId");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("WeddingPlannerAgentRuns", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("MessageId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WeddingPlannerAuditEvents", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerBrandDnaDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandDnaVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("BrandDnaVersionId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("WeddingPlannerBrandDnaDecisions", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerBrandDnaVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ProducingAgentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProducingAgentRunId");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("WeddingPlannerBrandDnaVersions", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("SessionId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("WeddingPlannerConversationMessages", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerPlanningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("WorkspaceId");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("WeddingPlannerPlanningSessions", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentApprovedBrandDnaVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CurrentApprovedBrandDnaVersionId");

                    b.HasIndex("SourceSystem", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("WeddingPlannerWorkspaces", (string)null);
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdInventorySlot", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.ContentItem", "ContentItem")
                        .WithMany("AdInventorySlots")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserOpportunity", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdvertiserProgram", "AdvertiserProgram")
                        .WithMany("Opportunities")
                        .HasForeignKey("AdvertiserProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvertiserProgram");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserProgram", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany("Programs")
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.BlissMatch", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdvertiserOpportunity", "AdvertiserOpportunity")
                        .WithMany("BlissMatches")
                        .HasForeignKey("AdvertiserOpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany("BlissMatches")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.RuleVersion", "RuleVersion")
                        .WithMany("BlissMatches")
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvertiserOpportunity");

                    b.Navigation("Creator");

                    b.Navigation("RuleVersion");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdvertiserOpportunity", "AdvertiserOpportunity")
                        .WithMany()
                        .HasForeignKey("AdvertiserOpportunityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdvertiserOpportunity");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CampaignPlacement", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdInventorySlot", "AdInventorySlot")
                        .WithMany("CampaignPlacements")
                        .HasForeignKey("AdInventorySlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.BlissMatch", "BlissMatch")
                        .WithMany()
                        .HasForeignKey("BlissMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bliss.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Placements")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.ContentItem", "ContentItem")
                        .WithMany("CampaignPlacements")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdInventorySlot");

                    b.Navigation("BlissMatch");

                    b.Navigation("Campaign");

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CampaignPlacementRun", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdInventorySlot", "AdInventorySlot")
                        .WithMany()
                        .HasForeignKey("AdInventorySlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.AdvertiserOpportunity", "AdvertiserOpportunity")
                        .WithMany()
                        .HasForeignKey("AdvertiserOpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.BlissMatch", "BlissMatch")
                        .WithMany()
                        .HasForeignKey("BlissMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.CampaignPlacement", "CampaignPlacement")
                        .WithMany()
                        .HasForeignKey("CampaignPlacementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.ContentItem", "ContentItem")
                        .WithMany()
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdInventorySlot");

                    b.Navigation("AdvertiserOpportunity");

                    b.Navigation("BlissMatch");

                    b.Navigation("Campaign");

                    b.Navigation("CampaignPlacement");

                    b.Navigation("ContentItem");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.ContentItem", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany("ContentItems")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CreatorIngestionRun", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.CreatorPlatform", "CreatorPlatform")
                        .WithMany()
                        .HasForeignKey("CreatorPlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("CreatorPlatform");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.CreatorPlatform", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany("Platforms")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.EligibilityCheck", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.BlissMatch", "BlissMatch")
                        .WithMany("EligibilityChecks")
                        .HasForeignKey("BlissMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlissMatch");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchEvaluationRun", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.BlissMatch", "BlissMatch")
                        .WithMany()
                        .HasForeignKey("BlissMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.RuleVersion", "RuleVersion")
                        .WithMany()
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlissMatch");

                    b.Navigation("Creator");

                    b.Navigation("RuleVersion");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchFormationRun", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdvertiserOpportunity", "AdvertiserOpportunity")
                        .WithMany()
                        .HasForeignKey("AdvertiserOpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.BlissMatch", "BlissMatch")
                        .WithMany()
                        .HasForeignKey("BlissMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.RuleVersion", "RuleVersion")
                        .WithMany()
                        .HasForeignKey("RuleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvertiserOpportunity");

                    b.Navigation("BlissMatch");

                    b.Navigation("Creator");

                    b.Navigation("RuleVersion");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchReviewDecision", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.BlissMatch", "BlissMatch")
                        .WithMany()
                        .HasForeignKey("BlissMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.MatchEvaluationRun", "MatchEvaluationRun")
                        .WithMany()
                        .HasForeignKey("MatchEvaluationRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BlissMatch");

                    b.Navigation("Creator");

                    b.Navigation("MatchEvaluationRun");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.MatchScoreComponent", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.BlissMatch", "BlissMatch")
                        .WithMany("ScoreComponents")
                        .HasForeignKey("BlissMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlissMatch");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.NetworkAccess", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany("NetworkAccesses")
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.AffiliateNetwork", "AffiliateNetwork")
                        .WithMany("NetworkAccesses")
                        .HasForeignKey("AffiliateNetworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");

                    b.Navigation("AffiliateNetwork");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.ProgramAccess", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.AdvertiserProgram", "AdvertiserProgram")
                        .WithMany("ProgramAccesses")
                        .HasForeignKey("AdvertiserProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvertiserProgram");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerAgentRun", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany()
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerBrandDnaVersion", "OutputBrandDnaVersion")
                        .WithMany()
                        .HasForeignKey("OutputBrandDnaVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerConversationMessage", "OutputMessage")
                        .WithMany()
                        .HasForeignKey("OutputMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerPlanningSession", "Session")
                        .WithMany("AgentRuns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerConversationMessage", "TriggerMessage")
                        .WithMany()
                        .HasForeignKey("TriggerMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_WeddingPlannerAgentRuns_WeddingPlannerConversationMessages~1");

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerWorkspace", "Workspace")
                        .WithMany("AgentRuns")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");

                    b.Navigation("OutputBrandDnaVersion");

                    b.Navigation("OutputMessage");

                    b.Navigation("Session");

                    b.Navigation("TriggerMessage");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerAuditEvent", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany()
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerConversationMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerPlanningSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerWorkspace", "Workspace")
                        .WithMany("AuditEvents")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Advertiser");

                    b.Navigation("Message");

                    b.Navigation("Session");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerBrandDnaDecision", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany()
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerBrandDnaVersion", "BrandDnaVersion")
                        .WithMany("Decisions")
                        .HasForeignKey("BrandDnaVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerWorkspace", "Workspace")
                        .WithMany("BrandDnaDecisions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");

                    b.Navigation("BrandDnaVersion");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerBrandDnaVersion", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany()
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerAgentRun", "ProducingAgentRun")
                        .WithMany()
                        .HasForeignKey("ProducingAgentRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerWorkspace", "Workspace")
                        .WithMany("BrandDnaVersions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");

                    b.Navigation("ProducingAgentRun");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerConversationMessage", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany()
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerPlanningSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerWorkspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");

                    b.Navigation("Session");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerPlanningSession", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany()
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerWorkspace", "Workspace")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertiser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerWorkspace", b =>
                {
                    b.HasOne("Bliss.Domain.Entities.Advertiser", "Advertiser")
                        .WithMany("WeddingPlannerWorkspaces")
                        .HasForeignKey("AdvertiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bliss.Domain.Entities.WeddingPlannerBrandDnaVersion", "CurrentApprovedBrandDnaVersion")
                        .WithMany()
                        .HasForeignKey("CurrentApprovedBrandDnaVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Advertiser");

                    b.Navigation("CurrentApprovedBrandDnaVersion");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdInventorySlot", b =>
                {
                    b.Navigation("CampaignPlacements");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Advertiser", b =>
                {
                    b.Navigation("NetworkAccesses");

                    b.Navigation("Programs");

                    b.Navigation("WeddingPlannerWorkspaces");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserOpportunity", b =>
                {
                    b.Navigation("BlissMatches");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AdvertiserProgram", b =>
                {
                    b.Navigation("Opportunities");

                    b.Navigation("ProgramAccesses");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.AffiliateNetwork", b =>
                {
                    b.Navigation("NetworkAccesses");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.BlissMatch", b =>
                {
                    b.Navigation("EligibilityChecks");

                    b.Navigation("ScoreComponents");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Placements");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.ContentItem", b =>
                {
                    b.Navigation("AdInventorySlots");

                    b.Navigation("CampaignPlacements");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.Creator", b =>
                {
                    b.Navigation("BlissMatches");

                    b.Navigation("ContentItems");

                    b.Navigation("Platforms");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.RuleVersion", b =>
                {
                    b.Navigation("BlissMatches");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerBrandDnaVersion", b =>
                {
                    b.Navigation("Decisions");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerPlanningSession", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Bliss.Domain.Entities.WeddingPlannerWorkspace", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("AuditEvents");

                    b.Navigation("BrandDnaDecisions");

                    b.Navigation("BrandDnaVersions");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
